apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-extender
  template:
    metadata:
      labels:
        app: scheduler-extender
    spec:
      containers:
        - image: zhengyscn/scheduler-extender:v1.0.5
          imagePullPolicy: IfNotPresent
          name: scheduler-extender
          command: ["/app/bin/scheduler-extender"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
              httpGet:
                  path: /healthz
                  port: 8000
              initialDelaySeconds: 10
              timeoutSeconds: 1