apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-extender
  template:
    metadata:
      labels:
        app: scheduler-extender
    spec:
      serviceAccountName: my-sa
      containers:
        - image: zhengyscn/scheduler-extender:v1.0.11
          imagePullPolicy: IfNotPresent
          name: scheduler-extender
          args:
            - -port=8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 30

      nodeName: master