apiVersion: v1
kind: Service
metadata:
  name: scheduler-extender
  namespace: default
spec:
  ports:
    - name: tcp-8000
      nodePort: 31234
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: scheduler-extender
  type: NodePort