apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
extenders:
  - urlPrefix: http://10.112.0.26:31234/scheduler/extender # node节点的ip地址
    filterVerb: filter
    prioritizeVerb: prioritize
    weight: 5
    enableHTTPS: false
    nodeCacheCapable: true
    ignorable: false